hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "config/craftpresence.json"

[[files]]
file = "config/desiredservers/desiredservers.json"

[[files]]
file = "config/emojiful-client.toml"

[[files]]
file = "config/fancymenu/assets/icon.icns"

[[files]]
file = "config/fancymenu/assets/icon16x16.png"

[[files]]
file = "config/fancymenu/assets/icon32x32.png"

[[files]]
file = "config/fancymenu/assets/logo.png"

[[files]]
file = "config/fancymenu/customizablemenus.txt"

[[files]]
file = "config/fancymenu/customization/drippy_loading_overlay_layout.txt"

[[files]]
file = "config/fancymenu/customization/title_screen_layout.txt"

[[files]]
file = "config/fancymenu/options.txt"

[[files]]
file = "config/figura.json"

[[files]]
file = "config/mimi-common.toml"

[[files]]
file = "config/paxi/resourcepacks/creeper-overhaul-overhaul.pw.toml"
metafile = true

[[files]]
file = "config/tectonic.json"

[[files]]
file = "mods/content/applied-energistics/ae2-qol-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/polymorphic-energistics.pw.toml"
metafile = true

[[files]]
file = "mods/content/applied-energistics/schematic-energistics.pw.toml"
metafile = true

[[files]]
file = "mods/content/build-deco/nightlights.pw.toml"
metafile = true

[[files]]
file = "mods/content/build-deco/shutters.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/advancedperipherals.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/ccsecureboot.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/classicperipherals.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/create-cc-total-logistics.pw.toml"
metafile = true

[[files]]
file = "mods/content/computer-craft/toms-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/blocks-bogies.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-aquatic-ambitions.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-bitterballen.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-central-kitchen.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-deepfried.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-dragons-plus.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-enchantable-machinery.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-enchantment-industry.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-integrated-farming.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-meta-logistics.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-more-pipe-bombs-in-packages.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-pattern-schematics.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-power-loader.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-railways-navigator.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-sound-of-steam.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-stock-bridge.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create-trading-floor.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/create.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/gears-n-kinetics.pw.toml"
metafile = true

[[files]]
file = "mods/content/create/hypertube.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure-catalog.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure-cmos.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure-expanded.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure-polaroid.pw.toml"
metafile = true

[[files]]
file = "mods/content/exposure/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/critters-and-companions.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/enderman-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/friends-and-foes-flowery-mooblooms-forge.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/friends-and-foes-forge.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/mavm.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/ribbits.pw.toml"
metafile = true

[[files]]
file = "mods/content/mobs/snuffles.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/joy-of-painting.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/leashedplayer.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/mimi.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/mmmmmmmmmmmm.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/moyai.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/mystical-oak-tree.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/sleep-tight.pw.toml"
metafile = true

[[files]]
file = "mods/content/other/straw-statues.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/content/supplementaries/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/almanac.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/balm.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/carrasconlib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cerbons-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/collective.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/configurable.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/connector.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/forgified-fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/guideme.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/kiwi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/mavapi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/melody.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/mru.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/paxi.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/txnilib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/unilib.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/libraries/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/performance/async-locator-refined.pw.toml"
metafile = true

[[files]]
file = "mods/performance/c2me-neoforge.pw.toml"
metafile = true

[[files]]
file = "mods/performance/createbetterfps.pw.toml"
metafile = true

[[files]]
file = "mods/performance/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/performance/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/performance/flerovium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/performance/krypton-foxified.pw.toml"
metafile = true

[[files]]
file = "mods/performance/ksyxis.pw.toml"
metafile = true

[[files]]
file = "mods/performance/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/performance/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/performance/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/performance/particle-core.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium/sodium-extras.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium/sodium-options-api.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium/sodium-options-mod-compat.pw.toml"
metafile = true

[[files]]
file = "mods/performance/sodium/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/cool-rain-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/dynamicsurroundingsfabric.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/audio/sound.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/armor-statues.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/cat_jam.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/cerbons-better-beacons.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/companion.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/crawl.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/grass-seeds.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/ironfish.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/lmd.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/monsters-in-the-closet.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/netherportalfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/no-telemetry.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/passable-foliage.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/shulker-drops-two.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/skippy-pearls.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/snow-under-trees.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/softer-hay-bales.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/spyglass-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/treechop.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/unloaded-activity.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gameplay/vivecraft.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/cubes-without-borders.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/dark-window-bar.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/distinguished-potions.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/emi/distraction-free-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/emi/emi-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/emi/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/emi/emi.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/emi/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/emi/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/emi/jei.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/scholar.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/screenshot-to-clipboard.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/gui/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/better-ping-display.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/emojiful.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/jade-addons-forge.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/jade.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/now-playing.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/overflowing-bars.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/hud/structure-credits.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/map/journeymap/journeylocator.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/map/journeymap/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/map/xaeros/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/map/xaeros/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/catalogue.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/craftpresence.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/default-options.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/desired-servers.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/drippy-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/exportstats.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/hide-experimental-warning.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/no-resource-pack-warnings-forge.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/menu/searchstats.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/bettergrassify.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/colorwheel-patcher.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/colorwheel.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/figura.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/figurasvc.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/highlight.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/iris.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/particular-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/seamless.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/sodium-dynamic-lights.pw.toml"
metafile = true

[[files]]
file = "mods/tweaks/visual/visuality-forge.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/spark.pw.toml"
metafile = true

[[files]]
file = "mods/utilities/worldedit.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/end/end-villager-outpost.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/end/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/nether/amplified-nether.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/overworld/expanded-ecosphere-server.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/overworld/expanded-ecosphere.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/overworld/fsmp-worldgen.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/overworld/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/worldgen/yungs/yungs-extras.pw.toml"
metafile = true

[[files]]
file = "unsup.ini"

[[files]]
file = "unsup.toml"
